feat: implements sonar

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -24,6 +24,17 @@ jobs:
 
     steps:
       - name: Wait for SonarCloud status
-        uses: chrispat/wait-for-sonarcloud-action@v1
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          while [[ "$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PULL_REQUEST_ID/checks | jq -r ".check_runs[] | select(.app.slug == \"sonarcloud\") | .conclusion")" == "null" ]]; do
+            echo "Waiting for SonarCloud analysis to complete..."
+            sleep 10
+          done
+
+          status=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PULL_REQUEST_ID/checks | jq -r ".check_runs[] | select(.app.slug == \"sonarcloud\") | .conclusion")
+
+          if [ "$status" != "success" ]; then
+            echo "SonarCloud analysis failed. Exiting..."
+            exit 1
+          else
+            echo "SonarCloud analysis successful. Continuing..."
+          fi
